FROM golang:1

ARG GITHUB_USERNAME
ARG GITHUB_TOKEN

ENV PROJECT=concept-exporter
WORKDIR /${PROJECT}

RUN echo "Fetching dependencies..." \
    && git clone https://github.com/vishnubob/wait-for-it.git \
    && cd wait-for-it \
    && mv ./wait-for-it.sh /${PROJECT} \
    && git config --global url."https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

COPY go.mod /
COPY go.sum /
RUN go mod download

COPY . .

ENTRYPOINT ["./wait-for-it.sh", "neo4j:7474", "-t", "60", "--"]
