FROM golang:1

ENV PROJECT=concept-exporter
WORKDIR /${PROJECT}

RUN echo "Fetching dependencies..." \
    && git clone https://github.com/vishnubob/wait-for-it.git \
    && cd wait-for-it \
    && mv ./wait-for-it.sh /${PROJECT}

COPY go.mod /
COPY go.sum /
RUN go mod download

COPY . .

ENTRYPOINT ["./wait-for-it.sh", "neo4j:7474", "-t", "60", "--"]
