# Default values for concept-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
eksCluster: false
replicaCount: 1
image:
  repository: coco/concept-exporter
  version: "" # should be set explicitly at installation
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 500Mi
  limits:
    memory: 1Gi
env:
  goroutines: "100"
  s3Writer:
    baseUrl: "http://upp-exports-rw-s3:8080"
